# Generated by Django 4.1.1 on 2022-10-13 10:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ContestQuestions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contest_id', models.CharField(max_length=100)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('easy', models.IntegerField()),
                ('medium', models.IntegerField()),
                ('hard', models.IntegerField()),
                ('topic', models.CharField(choices=[('array', 'Array'), ('string', 'String'), ('hash-table', 'Hash Table'), ('dynamic-progrmming', 'Dynamic Programming'), ('math', 'Math'), ('sorting', 'Sorting'), ('greedy', 'Greedy'), ('depth-first-search', 'Depth-First Search'), ('database', 'Database'), ('breadth-first-search', 'Breadth-First Search'), ('tree', 'Tree'), ('binary-search', 'Binary Search'), ('matrix', 'Matrix'), ('binary-tree', 'Binary Tree'), ('two-pointers', 'Two Pointers'), ('bit-manipulation', 'Bit Manipulation'), ('stack', 'Stack'), ('heap-priority-queue', 'Heap (Priority Queue)'), ('design', 'Design'), ('graph', 'Graph'), ('simulation', 'Simulation'), ('prefix-sum', 'Prefix Sum'), ('backtracking', 'Backtracking'), ('counting', 'Counting'), ('sliding-window', 'Sliding Window'), ('union-find', 'Union Find'), ('linked-list', 'Linked List'), ('ordered-set', 'Ordered Set'), ('monotonic-stack', 'Monotonic Stack'), ('recursion', 'Recursion'), ('enumeration', 'Enumeration'), ('trie', 'Trie'), ('divide-and-conquer', 'Divide and Conquer'), ('binary-search-tree', 'Binary Search Tree'), ('bitmask', 'Bitmask'), ('queue', 'Queue'), ('memoization', 'Memoization'), ('topological-sort', 'Topological Sort'), ('geometry', 'Geometry'), ('segment-tree', 'Segment Tree'), ('hash-function', 'Hash Function'), ('game-theory', 'Game Theory'), ('binary-indexed-tree', 'Binary Indexed Tree'), ('number-theory', 'Number Theory'), ('interactive', 'Interactive'), ('string-matching', 'String Matching'), ('rolling-hash', 'Rolling Hash'), ('data-stream', 'Data Stream'), ('shortest-path', 'Shortest Path'), ('combinatorics', 'Combinatorics'), ('randomized', 'Randomized'), ('brainteaser', 'Brainteaser'), ('monotonic-queue', 'Monotonic Queue'), ('merge-sort', 'Merge Sort'), ('iterator', 'Iterator'), ('concurrency', 'Concurrency'), ('doubly-linked-list', 'Doubly-Linked List'), ('probability-and-statistics', 'Probability and Statistics'), ('quickselect', 'Quickselect'), ('bucket-sort', 'Bucket Sort'), ('suffix-array', 'Suffix Array'), ('minimum-spanning-tree', 'Minimum Spanning Tree'), ('counting-sort', 'Counting Sort')], default='array', max_length=50)),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['created_on'],
            },
        ),
    ]
